# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Client Name')),
            ],
            options={
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Medium Name')),
            ],
            options={
                'verbose_name_plural': 'Media',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Project Title')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
                ('project_url', models.URLField(verbose_name='Project URL')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('completion_date', models.DateField()),
                ('in_development', models.BooleanField()),
                ('is_public', models.BooleanField(default=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=250, verbose_name='Meta Keywords')),
                ('project_image', models.ImageField(upload_to='projects')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Client')),
                ('media', models.ManyToManyField(to='work.Medium')),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ['-completion_date'],
            },
        ),
    ]
