# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='data_group',
            field=models.CharField(default='tech', max_length=150, verbose_name='Item Data Group Media'),
        ),
    ]
