# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jatto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name_plural': 'Skills'},
        ),
        migrations.AddField(
            model_name='about',
            name='home_town',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='about',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='phone_number',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='aboutfeed',
            name='client_feed',
            field=models.TextField(max_length=120),
        ),
    ]
