# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['title'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='name',
            new_name='title',
        ),
    ]
